<a href="https://colab.research.google.com/github/Paulie-Aditya/ml_practice/blob/main/kaggle_grind.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import requests

In [13]:
api_key = "ea9619c25a8b11f45b407b68b3f95379"
page_no = 1
#url = f'https://api.themoviedb.org/3/movie/top_rated?api_key={api_key}&language=en-US&page={page_no}'

url = f'https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={page_no}'

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlYTk2MTljMjVhOGIxMWY0NWI0MDdiNjhiM2Y5NTM3OSIsInN1YiI6IjY0ZTkwZjNiYzYxM2NlMDBjOWYxZTg5NiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.MYC9gwCgb20W6JMAvlCUfrxcssbpukISvRt33tJtxVA"
}

response = requests.get(url, headers=headers)
print(response.text)

{"page":1,"results":[{"adult":false,"backdrop_path":"/tmU7GeKVybMWFButWEGl2M4GeiP.jpg","genre_ids":[18,80],"id":238,"original_language":"en","original_title":"The Godfather","overview":"Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.","popularity":123.773,"poster_path":"/3bhkrj58Vtu7enYsRolD1fZdja1.jpg","release_date":"1972-03-14","title":"The Godfather","video":false,"vote_average":8.7,"vote_count":18479},{"adult":false,"backdrop_path":"/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg","genre_ids":[18,80],"id":278,"original_language":"en","original_title":"The Shawshank Redemption","overview":"Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.","popularity":132.698,"poster_path":"/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg","release_date":"1994-09-23","title":"The Shawshank Redemption","video":false,"vote_average":8.7,"vote_count":24413},{"adult":false,"backdrop_path":"/oo4PVK6AyLZN49BokxDFGyclN86.jpg","genre_ids":[18,80],"id":240,"original_language":"en","original_title":"The Godfather Part II","overview":"In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.","popularity":91.909,"poster_path":"/bMadFzhjy9T7R8J48QGq1ngWNAK.jpg","release_date":"1974-12-20","title":"The Godfather Part II","video":false,"vote_average":8.6,"vote_count":11167},{"adult":false,"backdrop_path":"/zb6fM1CX41D9rF9hdgclu0peUmy.jpg","genre_ids":[18,36,10752],"id":424,"original_language":"en","original_title":"Schindler's List","overview":"The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.","popularity":61.483,"poster_path":"/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg","release_date":"1993-12-15","title":"Schindler's List","video":false,"vote_average":8.6,"vote_count":14439},{"adult":false,"backdrop_path":"/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg","genre_ids":[35,18,10749],"id":19404,"original_language":"hi","original_title":"दिलवाले दुल्हनिया ले जायेंगे","overview":"Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.","popularity":52.514,"poster_path":"/ktejodbcdCPXbMMdnpI9BUxW6O8.jpg","release_date":"1995-10-20","title":"Dilwale Dulhania Le Jayenge","video":false,"vote_average":8.6,"vote_count":4228},{"adult":false,"backdrop_path":"/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg","genre_ids":[16,10751,14],"id":129,"original_language":"ja","original_title":"千と千尋の神隠し","overview":"A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.","popularity":86.543,"poster_path":"/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg","release_date":"2001-07-20","title":"Spirited Away","video":false,"vote_average":8.5,"vote_count":14757},{"adult":false,"backdrop_path":"/qqHQsStV6exghCM7zbObuYBiYxw.jpg","genre_ids":[18],"id":389,"original_language":"en","original_title":"12 Angry Men","overview":"The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.","popularity":62.74,"poster_path":"/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg","release_date":"1957-04-10","title":"12 Angry Men","video":false,"vote_average":8.5,"vote_count":7549},{"adult":false,"backdrop_path":"/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg","genre_ids":[10749,16,18],"id":372058,"original_language":"ja","original_title":"君の名は。","overview":"High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.","popularity":106.407,"poster_path":"/q719jXXEzOoYaps6babgKnONONX.jpg","release_date":"2016-08-26","title":"Your Name.","video":false,"vote_average":8.5,"vote_count":10178},{"adult":false,"backdrop_path":"/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg","genre_ids":[35,53,18],"id":496243,"original_language":"ko","original_title":"기생충","overview":"All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.","popularity":78.578,"poster_path":"/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg","release_date":"2019-05-30","title":"Parasite","video":false,"vote_average":8.5,"vote_count":16245},{"adult":false,"backdrop_path":"/dqK9Hag1054tghRQSqLSfrkvQnA.jpg","genre_ids":[18,28,80,53],"id":155,"original_language":"en","original_title":"The Dark Knight","overview":"Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.","popularity":123.905,"poster_path":"/qJ2tW6WMUDux911r6m7haRef0WH.jpg","release_date":"2008-07-14","title":"The Dark Knight","video":false,"vote_average":8.5,"vote_count":30377},{"adult":false,"backdrop_path":"/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg","genre_ids":[14,18,80],"id":497,"original_language":"en","original_title":"The Green Mile","overview":"A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.","popularity":76.567,"poster_path":"/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg","release_date":"1999-12-10","title":"The Green Mile","video":false,"vote_average":8.5,"vote_count":15792},{"adult":false,"backdrop_path":"/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg","genre_ids":[53,80],"id":680,"original_language":"en","original_title":"Pulp Fiction","overview":"A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.","popularity":83.217,"poster_path":"/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg","release_date":"1994-09-10","title":"Pulp Fiction","video":false,"vote_average":8.5,"vote_count":25713},{"adult":false,"backdrop_path":"/qdIMHd4sEfJSckfVJfKQvisL02a.jpg","genre_ids":[35,18,10749],"id":13,"original_language":"en","original_title":"Forrest Gump","overview":"A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.","popularity":89.073,"poster_path":"/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg","release_date":"1994-06-23","title":"Forrest Gump","video":false,"vote_average":8.5,"vote_count":25207},{"adult":false,"backdrop_path":"/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg","genre_ids":[12,14,28],"id":122,"original_language":"en","original_title":"The Lord of the Rings: The Return of the King","overview":"Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.","popularity":98.276,"poster_path":"/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg","release_date":"2003-12-01","title":"The Lord of the Rings: The Return of the King","video":false,"vote_average":8.5,"vote_count":22081},{"adult":false,"backdrop_path":"/eoCSp75lxatmIa6aGqfnzwtbttd.jpg","genre_ids":[37],"id":429,"original_language":"it","original_title":"Il buono, il brutto, il cattivo","overview":"While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.","popularity":69.787,"poster_path":"/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg","release_date":"1966-12-23","title":"The Good, the Bad and the Ugly","video":false,"vote_average":8.5,"vote_count":7662},{"adult":false,"backdrop_path":"/sw7mordbZxgITU877yTpZCud90M.jpg","genre_ids":[18,80],"id":769,"original_language":"en","original_title":"GoodFellas","overview":"The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.","popularity":66.806,"poster_path":"/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg","release_date":"1990-09-12","title":"GoodFellas","video":false,"vote_average":8.5,"vote_count":11615},{"adult":false,"backdrop_path":"/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg","genre_ids":[16,28,12],"id":569094,"original_language":"en","original_title":"Spider-Man: Across the Spider-Verse","overview":"After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.","popularity":2433.631,"poster_path":"/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg","release_date":"2023-05-31","title":"Spider-Man: Across the Spider-Verse","video":false,"vote_average":8.5,"vote_count":3722},{"adult":false,"backdrop_path":"/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg","genre_ids":[18,10749],"id":11216,"original_language":"it","original_title":"Nuovo Cinema Paradiso","overview":"A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.","popularity":46.571,"poster_path":"/rf99GAg2zHKFj79QKn8ed8iPCVF.jpg","release_date":"1988-11-17","title":"Cinema Paradiso","video":false,"vote_average":8.5,"vote_count":3904},{"adult":false,"backdrop_path":"/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg","genre_ids":[35,18],"id":637,"original_language":"it","original_title":"La vita è bella","overview":"A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.","popularity":62.433,"poster_path":"/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg","release_date":"1997-12-20","title":"Life Is Beautiful","video":false,"vote_average":8.5,"vote_count":12122},{"adult":false,"backdrop_path":"/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg","genre_ids":[28,18],"id":346,"original_language":"ja","original_title":"七人の侍","overview":"A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.","popularity":36.754,"poster_path":"/iAq0sq42vKTLneVGqHn1D4GzgrM.jpg","release_date":"1954-04-26","title":"Seven Samurai","video":false,"vote_average":8.5,"vote_count":3181}],"total_pages":571,"total_results":11406}

In [14]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [15]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,123.773,8.7,18479
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,132.698,8.7,24413
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,91.909,8.6,11167
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,61.483,8.6,14439
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,52.514,8.6,4228

In [17]:
temp_df.shape

(20, 7)

In [18]:
df = pd.DataFrame()

In [28]:
for i in range(1,100):
    response = requests.get(f'https://api.themoviedb.org/3/movie/top_rated?api_key={api_key}&language=en-US&page={i}')
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat((df,temp_df),ignore_index=True)

In [29]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,123.773,8.7,18479
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,132.698,8.7,24413
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,91.909,8.6,11167
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,61.483,8.6,14439
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,52.514,8.6,4228
...,...,...,...,...,...,...,...
16455,13004,Barbie and the Diamond Castle,Liana and Alexa (Barbie and Teresa) are best f...,2008-09-03,29.638,7.4,766
16456,9065,Europa,"A young, idealist American gets a job as a tra...",1991-06-27,7.196,7.4,265
16457,7863,Shine,"Pianist David Helfgott, driven by his father a...",1996-08-15,10.150,7.4,577
16458,65754,The Girl with the Dragon Tattoo,This English-language adaptation of the Swedis...,2011-12-14,27.219,7.4,6426
16459,57361,The Yellow Sea,A Korean man in China takes an assassination j...,2010-12-22,10.003,7.4,432

In [30]:
df.shape

(16460, 7)

In [31]:
df.to_csv('movies.csv')